- name: "Create directories"
  file: path={{ item.path }} state=directory recurse=yes owner={{ item.owner }} group={{ item.group }} mode=0755
  loop:
    - { path: "/etc/liri/www/snippets", owner: "root", group: "root" }
    - { path: "/srv/www/liri.io", owner: "liri", group: "liri" }
    - { path: "/srv/www/docs.liri.io", owner: "liri", group: "liri" }
    - { path: "/srv/www/build.liri.io", owner: "root", group: "root" }
    - { path: "/srv/www/repo.liri.io/artifacts", owner: "liri", group: "liri" }
    - { path: "/srv/www/repo.liri.io/artifacts/master", owner: "liri", group: "liri" }
    - { path: "/srv/www/repo.liri.io/artifacts/develop", owner: "liri", group: "liri" }
    - { path: "/var/log/nginx/liri.io", owner: "root", group: "root" }
    - { path: "/var/log/nginx/build.liri.io", owner: "root", group: "root" }
    - { path: "/var/log/nginx/repo.liri.io", owner: "root", group: "root" }

- name: "Copy favicon.ico"
  get_url:
    url: https://raw.githubusercontent.com/lirios/lirios.github.io/master/favicon.ico
    dest: "/srv/www/{{ item }}/favicon.ico"
    mode: 0644
  loop:
    - build.liri.io
    - repo.liri.io

- name: "Copy configuration"
  copy: src={{ item.src }} dest={{ item.dest }} mode=0644
  loop:
    - { src: "compose.yml", dest: "/etc/liri/www/docker-compose.yml" }
    - { src: "nginx.conf", dest: "/etc/liri/www/nginx.conf" }
    - { src: "snippets/gzip.conf", dest: "/etc/liri/www/snippets/gzip.conf" }
    - { src: "snippets/expires.conf", dest: "/etc/liri/www/snippets/expires.conf" }
    - { src: "www.service", dest: "/etc/systemd/system/www.service" }

- name: "Restart service"
  shell: systemctl enable www.service && systemctl daemon-reload && systemctl restart www.service
  #systemd: name=www.service state=restarted enabled=True
